name: Suggestion
description: Request the feature you want
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: "What feature do you want?"
    validations:
      required: true
